### ISSUE TITLE
Création composant

### ISSUE THREAD

**Issue by valentinchevalier** [valentinchevalier/projetM1-tardis#11]
En tant que : Utilisateur
Je souhaite : Pouvoir créer un composant
Afin de : Ajouter un composant au modèle 

Test d'acceptations :
Given : L'interface graphique
When : Je clique sur le bouton d'ajout de composant
And : Je clique à l'endroit ou je veux l'ajouter
And : Je saisi son nom
Then : Le composant apparait

- [x] créer bouton 'ajout'
- [x] fenêtre pop-up pour demander le nom
- [x] sélectionner un emplacement

**Comment by SowKs** [comment]
Le bouton serait sur une barre d'action ou sur l'interface ?
