### ISSUE TITLE
Création d'une barre d'outils évolutive

### ISSUE THREAD

**Issue by SowKs** [valentinchevalier/projetM1-tardis#22]
En tant que : Utilisateur
Je souhaite : Avoir un accès à une barre d'outils
Afin de : Manipuler les éléments par des menus de la barre d'outils

Given : Le projet
When : L'utilisateur lance l'outil d'édition
Then : L'outil possède une barre d'outil

Given : Le projet
When : L'utilisateur lance l'outil d'édition
Then : L'outil possède une barre d'outil avec trois menu : "Composant", "Connexion", "Port"

Given : L'outil d'édition
When : L'utilisateur clique sur un des menus de la barre d'outils
Then : Un menu déroulant s'affiche avec des menu item "Ajouter", "Modifer", "Supprimer"

- [x] Création de la barre d'outils

- [x] Ajout de trois menus "Composant", "Connexion", "Port"

- [x] Ajout de menu item "Ajouter", "Modifier", "Supprimer" à chaque menu

**Comment by valentinchevalier** [comment]
Il faudrait que vous remplissiez la description.
