### ISSUE TITLE
Méthode retournant l'élément sur lequel on clique

### ISSUE THREAD

**Issue by SowKs** [valentinchevalier/projetM1-tardis#29]
En tant que : Développeur
Je souhaite : Avoir un handler mouse pressed (clique droit) qui retourne l'élément présent à la position du clique sur l'interface ou vide si aucun élément n'est présent
Afin de : Faire un menu interactif en fonction de l'élément sélectionner

Given : L'outil d'édition
When : Clique droit sur l'interface
Then : Le type de l'élément et son nom est affiché

- [x] Event handler mouse pressed (clique droit) sur l'interface

- [x] Parcours des éléments et si un est présent à la position de l'event le retourner, vide sinon

**Comment by valentinchevalier** [comment]
Les technical stories ne sont normalement pas comptabilisés dans les estimations.
